# Generated by Django 5.2.4 on 2025-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
